### PR TITLE
Manifest

### PR DESCRIPTION
**Pull request by kane2931**
Some manifest entries are no longer needed. (was for old Roku OS).

[manifest.txt](https://github.com/sudo97/Roku-IPTV/files/1187503/manifest.txt)

### CODE REVIEW

**Comment by kane2931** [comment]
icon_focus_sd.png
icon_side_hd.png
icon_side_sd.png

splash_hd.jpg
splash_sd.jpg

are no longer required.

**Comment by kane2931** [comment]
MainScene.brs still have "hls" instead of "" for streamformat.

**Comment by sudo97** [comment]
I will take a closer look on it soon, seems like you've done a big job, I had no time for(actually spent about 30 minutes to write all of this). But I am not sure I am going to accept all of your improvements, in my main project I use different style and I enjoy it. But looking on the amount of job you have done -- my respect and congrats, you're probably an awesome pro :-)
Hope we can improve it in future. Give me few days to take a closer look. Thanks.

**Comment by sudo97** [comment]
You should always split xml and brs files, ALWAYS.
One of the reasons is: you can use one script many times, and also it is useful to use it this way in eclipse.
Thanks for a good job.

**Comment by sudo97** [comment]
Well, I wouldn't say this is a good code. You implemented things(which is great), but code-style is awful. Requires very big review. I accept your pull request, but I am going to need to rewrite many many things

**Comment by sudo97** [comment]
Sorry, but seems like you didn't test what you write, more like very clever copy&paste. I had to rewrite many many things to make it work together. Saving to registry didn't work, very inlogical use of regirstry at all. Too many task nodes, I removed one(probably should remove one more, but let it be). I can keep telling problems I see

**Pull request merged**
